### PR TITLE
Migrate to Gradle nature project

### PR DESCRIPTION
**Pull request by andre-paraense**
### Why was it necessary?
This PR was necessary to migrate MECA project to a Gradle nature project, in order to make it easier to be contributed and built, and also to organize dependencies and get them directly from MavenCentral repository, instead of libs directory, making it lighter to store in the repository and easier to evolve.

### How was it done?
We added the Gradle configuration files necessary and all the Maven libs tags, expect in the case of **cst** lib which is not available from Maven and had to stay in libs directory.

### How to test?

Probably the best way to test is to substitute another MECA project you had as dependency in one of your application by the one in this branch and see yourself that it works just as well.

### Future works

Next steps are to configure a continuos integration process in the repository and make MECA available from MavenCentral as well, so other aplications which are already built on top of it will benefit.

### CODE REVIEW

**Review by eduardofroes — DISMISSED** [review]

**Comment by rgudwin** [comment]
I don know exactly how to solve this, but I noticed that if someone is simply looking to this project, and decides to download and use it, all the dependencies from CST are not appearing here. If someone tries to use MECA and do not include the dependencies from CST, he/she will not succeed, because even though the cst.jar is provided here, the other dependencies are not. How can we solve that ?  Should we explicitly include all CST dependencies here ?

**Comment by rgudwin** [comment]
Also, I made a test, and the Gradle support plugin in Netbeans 8.2 creates a .nb-gradle directory. This directory should be included in the .gitignore, to avoid being commited. The same happens while compiling CST with Netbeans 8.2. The same does not happen with Apache Netbeans.

**Review by eduardofroes — APPROVED** [review]

**Review by eduardofroes — DISMISSED** [review]

**Comment by andre-paraense** [comment]
> I don know exactly how to solve this, but I noticed that if someone is simply looking to this project, and decides to download and use it, all the dependencies from CST are not appearing here. If someone tries to use MECA and do not include the dependencies from CST, he/she will not succeed, because even though the cst.jar is provided here, the other dependencies are not. How can we solve that ? Should we explicitly include all CST dependencies here ?

@rgudwin I substituted the fat .jar that existed before for the separated libraries! In the next steps, we will understand better how these dependencies will come from MavenCentral in the CST library, considering transitive dependencies or not ('api'vs 'implementation')

**Comment by andre-paraense** [comment]
> Also, I made a test, and the Gradle support plugin in Netbeans 8.2 creates a .nb-gradle directory. This directory should be included in the .gitignore, to avoid being commited. The same happens while compiling CST with Netbeans 8.2. The same does not happen with Apache Netbeans.

@rgudwin I added the .nb-gradle directory to the .gitignore file.

**Comment by rgudwin** [comment]
Shouldn't we use a reference to build.gradle instead of putting the libs in the libs directory, leaving to libs only those which are not available in MavenCentral ? Also, we should think about using the runtimeOnly configuration in build.gradle, instead of implementation. As I could understand, those configurations using implementation are required for compilation, but runtimeOnly is a dependency only for execution.

**Comment by andre-paraense** [comment]
> Shouldn't we use a reference to build.gradle instead of putting the libs in the libs directory, leaving to libs only those which are not available in MavenCentral ? Also, we should think about using the runtimeOnly configuration in build.gradle, instead of implementation. As I could understand, those configurations using implementation are required for compilation, but runtimeOnly is a dependency only for execution.

@rgudwin changed to get the libs from MavenCentrall. Regarding this 'runtimeOnly' things, as we are not sure of it, I belive we should not waste time with this now, as it will all change when CST gets to MavenCentral soon. Let's move on so we can have everything on MavenCentral as soon as possible.

**Review by rgudwin — APPROVED** [review]

**Review by eduardofroes — APPROVED** [review]

**Review by eduardofroes — APPROVED** [review]

**Pull request merged**
